### ISSUE TITLE
Expose in-app app drawer

### ISSUE THREAD

**Issue by MohammedAlamkhan** [bridgelauncher/launcher#2]
Please consider exposing the in-app app drawer so that it can be remapped to html button. In app app drawer is already a solid implementation and not in all use cases it makes sense to reinvent the wheel. while web framework can be used for aesthetic and customization purposes, exposed app drawer can be used for quick core functionality implementation(app launch)  without using floating bridge button.

**Comment by theothertored** [comment]
This is already implemented via `Bridge.requestOpenBridgeAppDrawer()`, does it not work on your device?

See the API typings file for all available functions with documentation comments:
https://github.com/bridgelauncher/api/blob/a554ff69c2d6bb4ff2bd90a6a8eed6b93812f1bb/Bridge.d.ts#L406

**Comment by MohammedAlamkhan** [comment]
Thanks!! I apologize i missed it.
