### ISSUE TITLE
Abnormal rendering of webpage width and height 

### ISSUE THREAD

**Issue by HusniMuhammad** [bridgelauncher/launcher#4]

**Comment by theothertored** [comment]
You need to provide information for me to reproduce the issue, for example a simple HTML file that demonstrates the issue alongside a screenshot. I can't do anything with this as-is.

**Comment by HusniMuhammad** [comment]
> You need to provide information for me to reproduce the issue, for example a simple HTML file that demonstrates the issue alongside a screenshot. I can't do anything with this as-is.

Ok
