### ISSUE TITLE
Redesign 

### ISSUE THREAD

**Issue by HusniMuhammad** [bridgelauncher/launcher#5]
Please consider redesigning this application as a html loader not as a launcher so users can navigate to different apps easily and develop websites with mobile devices 

Main purpose of this application would be serving local html files (other browser applications restricted this access in Android 11) 

Or suggest alternatives!

**Comment by theothertored** [comment]
This project is a launcher and I have no interest in turning it into some alternative app ecosystem. This entire project is open source, if you'd like to turn it into that, you're free to fork the code and do whatever you want with it.

Consider looking into Capacitor and other container software if you wanna build mobile apps using web technologies.
