### ISSUE TITLE
launch webbrowser with URL, or a way to invoke events and/or using shortcuts?

### ISSUE THREAD

**Issue by yesco** [bridgelauncher/launcher#8]
Just found this great project.

Finally, I can own my home screen.

To make it a more full launcher, I'd like to be able to create short-cuts to launch web-pages in a browser, or open specific Google Docs. I believe using intents is the way that works,, or  using shortcuts. However, I'm not privy to the workings of Androids API and java.

Also, apparently, there is an alluring way to open several webviews in one app. This would be cool to be able to build my own browser in html/javascript controlled from/integrated in the launcher.

**Comment by theothertored** [comment]
> I'd like to be able to create short-cuts to launch web-pages in a browser, or open specific Google Docs.

Opening links in an external browser should now be possible in [v0.0.5](https://github.com/bridgelauncher/launcher/releases/tag/v0.0.5-alpha) by using `target="_blank"` on an `<a>` tag or from JS.

> This would be cool to be able to build my own browser in html/javascript controlled from/integrated in the launcher.

I'm not interested in building a base for building a custom browser. Maybe you can fulfil your needs by using `<iframe>` to embed other webpages inside your own webpage.
